In [5]:
%pip install pandas --upgrade --quiet
%pip install numpy --upgrade --quiet

WARNING: Ignoring invalid distribution -umpy (/home/rushabh/.local/lib/python3.10/site-packages)
WARNING: Ignoring invalid distribution -umpy (/home/rushabh/.local/lib/python3.10/site-packages)
WARNING: Ignoring invalid distribution -umpy (/home/rushabh/.local/lib/python3.10/site-packages)
Note: you may need to restart the kernel to use updated packages.
WARNING: Ignoring invalid distribution -umpy (/home/rushabh/.local/lib/python3.10/site-packages)
WARNING: Ignoring invalid distribution -umpy (/home/rushabh/.local/lib/python3.10/site-packages)
WARNING: Ignoring invalid distribution -umpy (/home/rushabh/.local/lib/python3.10/site-packages)
Note: you may need to restart the kernel to use updated packages.

Importing pandas

In [6]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression 
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

Reading CSV file

In [7]:
CO2Emission=pd.read_csv('CO2 Emissions_Canada.csv')

Printing the data

In [8]:
CO2Emission

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...,...,...,...,...,...
7380,VOLVO,XC40 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,10.7,7.7,9.4,30,219
7381,VOLVO,XC60 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7382,VOLVO,XC60 T6 AWD,SUV - SMALL,2.0,4,AS8,Z,11.7,8.6,10.3,27,240
7383,VOLVO,XC90 T5 AWD,SUV - STANDARD,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7384,VOLVO,XC90 T6 AWD,SUV - STANDARD,2.0,4,AS8,Z,12.2,8.7,10.7,26,248

In [9]:
CO2Emission.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7385 entries, 0 to 7384
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Make                              7385 non-null   object
 1   Model                             7385 non-null   object
 2   Vehicle Class                     7385 non-null   object
 3   Engine Size(L)                    7385 non-null   float64
 4   Cylinders                         7385 non-null   int64
 5   Transmission                      7385 non-null   object
 6   Fuel Type                         7385 non-null   object
 7   Fuel Consumption City (L/100 km)  7385 non-null   float64
 8   Fuel Consumption Hwy (L/100 km)   7385 non-null   float64
 9   Fuel Consumption Comb (L/100 km)  7385 non-null   float64
 10  Fuel Consumption Comb (mpg)       7385 non-null   int64
 11  CO2 Emissions(g/km)               7385 non-null   int64
dtypes: float64(4), int64(3), object(5)
memory usage: 692.5+ KB

In [10]:
CO2Emission.describe()

,Engine Size(L),Cylinders,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
count,7385.000000,7385.000000,7385.000000,7385.000000,7385.000000,7385.000000,7385.000000
mean,3.160068,5.615030,12.556534,9.041706,10.975071,27.481652,250.584699
std,1.354170,1.828307,3.500274,2.224456,2.892506,7.231879,58.512679
min,0.900000,3.000000,4.200000,4.000000,4.100000,11.000000,96.000000
25%,2.000000,4.000000,10.100000,7.500000,8.900000,22.000000,208.000000
50%,3.000000,6.000000,12.100000,8.700000,10.600000,27.000000,246.000000
75%,3.700000,6.000000,14.600000,10.200000,12.600000,32.000000,288.000000
max,8.400000,16.000000,30.600000,20.600000,26.100000,69.000000,522.000000

To check NAN

In [11]:
nan_data=CO2Emission.isna()

Adding up all the nan data

In [12]:
nan_count=nan_data.sum()

In [13]:
nan_data

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
7380,False,False,False,False,False,False,False,False,False,False,False,False
7381,False,False,False,False,False,False,False,False,False,False,False,False
7382,False,False,False,False,False,False,False,False,False,False,False,False
7383,False,False,False,False,False,False,False,False,False,False,False,False
7384,False,False,False,False,False,False,False,False,False,False,False,False

Droping a model column

In [14]:
CO2Emission.drop(columns=['Model','Make','Vehicle Class','Transmission'],inplace=True)

In [15]:
CO2Emission

,Engine Size(L),Cylinders,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,2.0,4,Z,9.9,6.7,8.5,33,196
1,2.4,4,Z,11.2,7.7,9.6,29,221
2,1.5,4,Z,6.0,5.8,5.9,48,136
3,3.5,6,Z,12.7,9.1,11.1,25,255
4,3.5,6,Z,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...,...
7380,2.0,4,Z,10.7,7.7,9.4,30,219
7381,2.0,4,Z,11.2,8.3,9.9,29,232
7382,2.0,4,Z,11.7,8.6,10.3,27,240
7383,2.0,4,Z,11.2,8.3,9.9,29,232
7384,2.0,4,Z,12.2,8.7,10.7,26,248

In [16]:
CO2Emission=pd.get_dummies(CO2Emission,columns=['Fuel Type'],dtype=int)
CO2Emission

,Engine Size(L),Cylinders,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km),Fuel Type_D,Fuel Type_E,Fuel Type_N,Fuel Type_X,Fuel Type_Z
0,2.0,4,9.9,6.7,8.5,33,196,0,0,0,0,1
1,2.4,4,11.2,7.7,9.6,29,221,0,0,0,0,1
2,1.5,4,6.0,5.8,5.9,48,136,0,0,0,0,1
3,3.5,6,12.7,9.1,11.1,25,255,0,0,0,0,1
4,3.5,6,12.1,8.7,10.6,27,244,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
7380,2.0,4,10.7,7.7,9.4,30,219,0,0,0,0,1
7381,2.0,4,11.2,8.3,9.9,29,232,0,0,0,0,1
7382,2.0,4,11.7,8.6,10.3,27,240,0,0,0,0,1
7383,2.0,4,11.2,8.3,9.9,29,232,0,0,0,0,1
7384,2.0,4,12.2,8.7,10.7,26,248,0,0,0,0,1

test-split

In [17]:
CO2Emission_X=(CO2Emission.drop('CO2 Emissions(g/km)',axis=1))
CO2Emission_Y=(CO2Emission['CO2 Emissions(g/km)'])

In [18]:
CO2Emission_train,CO2Emission_test,CO2Emission_Y_train,CO2Emission_Y_test=train_test_split(CO2Emission_X,CO2Emission_Y,random_state=10,test_size=0.2)

In [19]:
print(CO2Emission_train)
print(CO2Emission_test)

      Engine Size(L)  Cylinders  Fuel Consumption City (L/100 km)  \
4129             2.0          4                              10.2
1843             2.1          4                               8.6
7342             1.8          4                               4.5
6992             3.0          6                              12.4
4186             1.8          4                               9.0
...              ...        ...                               ...
3441             3.0          6                              12.7
1344             6.2          8                              16.3
4623             5.3          8                              19.8
7293             2.4          4                              11.6
1289             3.6          6                              13.3

      Fuel Consumption Hwy (L/100 km)  Fuel Consumption Comb (L/100 km)  \
4129                              7.4                               9.0
1843                              5.9                               7.4
7342                              4.9                               4.7
6992                              8.8                              10.8
4186                              6.8                               8.0
...                               ...                               ...
3441                              9.1                              11.1
1344                             11.6                              14.2
4623                             13.9                              17.2
7293                              9.0                              10.4
1289                              8.8                              11.3

      Fuel Consumption Comb (mpg)  Fuel Type_D  Fuel Type_E  Fuel Type_N  \
4129                           31            0            0            0
1843                           38            1            0            0
7342                           60            0            0            0
6992                           26            0            0            0
4186                           35            0            0            0
...                           ...          ...          ...          ...
3441                           25            0            0            0
1344                           20            0            0            0
4623                           16            0            1            0
7293                           27            0            0            0
1289                           25            0            0            0

      Fuel Type_X  Fuel Type_Z
4129            0            1
1843            0            0
7342            1            0
6992            0            1
4186            1            0
...           ...          ...
3441            0            1
1344            0            1
4623            0            0
7293            1            0
1289            1            0

[5908 rows x 11 columns]
      Engine Size(L)  Cylinders  Fuel Consumption City (L/100 km)  \
5862             5.3          8                              15.8
2049             3.6          6                              14.6
4392             6.0         12                              17.5
4497             2.0          4                              11.0
4954             3.0          6                              14.0
...              ...        ...                               ...
4588             1.8          4                               4.8
6165             4.0          8                              16.0
5612             3.6          6                              12.3
1068             3.0          6                              13.4
704              3.7          6                              14.3

      Fuel Consumption Hwy (L/100 km)  Fuel Consumption Comb (L/100 km)  \
5862                             11.4                              13.8
2049                             10.1                              12.6
4392                             11.4                              14.7
4497                              7.7                               9.5
4954                              9.4                              11.9
...                               ...                               ...
4588                              5.5                               5.1
6165                             10.5                              13.5
5612                              8.2                              10.4
1068                              9.8                              11.8
704                              10.6                              12.6

      Fuel Consumption Comb (mpg)  Fuel Type_D  Fuel Type_E  Fuel Type_N  \
5862                           20            0            0            0
2049                           22            0            0            0
4392                           19            0            0            0
4497                           30            0            0            0
4954                           24            0            0            0
...                           ...          ...          ...          ...
4588                           55            0            0            0
6165                           21            0            0            0
5612                           27            0            0            0
1068                           24            0            0            0
704                            22            0            0            0

      Fuel Type_X  Fuel Type_Z
5862            1            0
2049            1            0
4392            0            1
4497            0            1
4954            0            1
...           ...          ...
4588            1            0
6165            0            1
5612            1            0
1068            1            0
704             1            0

[1477 rows x 11 columns]

In [20]:
model=LinearRegression()
model.fit(CO2Emission_train,CO2Emission_Y_train)

LinearRegression()

In [21]:
mean_squared_error(CO2Emission_Y_train, model.predict(CO2Emission_train))

23.739580396045856

In [22]:
mean_squared_error(CO2Emission_Y_test, model.predict(CO2Emission_test))

28.088756621088645